package org.linlinjava.litemall.db.bot.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class BotCustomerDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_customer_detail.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_customer_detail.bind_id
     *
     * @mbg.generated
     */
    private String bindId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_customer_detail.bot_type
     *
     * @mbg.generated
     */
    private Integer botType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_customer_detail.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_customer_detail.contact_id
     *
     * @mbg.generated
     */
    private String contactId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_customer_detail.contact_type
     *
     * @mbg.generated
     */
    private Integer contactType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_customer_detail.contack_org_type
     *
     * @mbg.generated
     */
    private Integer contackOrgType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_customer_detail.nick_name
     *
     * @mbg.generated
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_customer_detail.tel_num
     *
     * @mbg.generated
     */
    private String telNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_customer_detail.contack_ext
     *
     * @mbg.generated
     */
    private String contackExt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_customer_detail.sync_time
     *
     * @mbg.generated
     */
    private LocalDateTime syncTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_customer_detail.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_customer_detail.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_customer_detail.id
     *
     * @return the value of bot_customer_detail.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_customer_detail.id
     *
     * @param id the value for bot_customer_detail.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_customer_detail.bind_id
     *
     * @return the value of bot_customer_detail.bind_id
     *
     * @mbg.generated
     */
    public String getBindId() {
        return bindId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_customer_detail.bind_id
     *
     * @param bindId the value for bot_customer_detail.bind_id
     *
     * @mbg.generated
     */
    public void setBindId(String bindId) {
        this.bindId = bindId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_customer_detail.bot_type
     *
     * @return the value of bot_customer_detail.bot_type
     *
     * @mbg.generated
     */
    public Integer getBotType() {
        return botType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_customer_detail.bot_type
     *
     * @param botType the value for bot_customer_detail.bot_type
     *
     * @mbg.generated
     */
    public void setBotType(Integer botType) {
        this.botType = botType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_customer_detail.name
     *
     * @return the value of bot_customer_detail.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_customer_detail.name
     *
     * @param name the value for bot_customer_detail.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_customer_detail.contact_id
     *
     * @return the value of bot_customer_detail.contact_id
     *
     * @mbg.generated
     */
    public String getContactId() {
        return contactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_customer_detail.contact_id
     *
     * @param contactId the value for bot_customer_detail.contact_id
     *
     * @mbg.generated
     */
    public void setContactId(String contactId) {
        this.contactId = contactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_customer_detail.contact_type
     *
     * @return the value of bot_customer_detail.contact_type
     *
     * @mbg.generated
     */
    public Integer getContactType() {
        return contactType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_customer_detail.contact_type
     *
     * @param contactType the value for bot_customer_detail.contact_type
     *
     * @mbg.generated
     */
    public void setContactType(Integer contactType) {
        this.contactType = contactType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_customer_detail.contack_org_type
     *
     * @return the value of bot_customer_detail.contack_org_type
     *
     * @mbg.generated
     */
    public Integer getContackOrgType() {
        return contackOrgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_customer_detail.contack_org_type
     *
     * @param contackOrgType the value for bot_customer_detail.contack_org_type
     *
     * @mbg.generated
     */
    public void setContackOrgType(Integer contackOrgType) {
        this.contackOrgType = contackOrgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_customer_detail.nick_name
     *
     * @return the value of bot_customer_detail.nick_name
     *
     * @mbg.generated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_customer_detail.nick_name
     *
     * @param nickName the value for bot_customer_detail.nick_name
     *
     * @mbg.generated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_customer_detail.tel_num
     *
     * @return the value of bot_customer_detail.tel_num
     *
     * @mbg.generated
     */
    public String getTelNum() {
        return telNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_customer_detail.tel_num
     *
     * @param telNum the value for bot_customer_detail.tel_num
     *
     * @mbg.generated
     */
    public void setTelNum(String telNum) {
        this.telNum = telNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_customer_detail.contack_ext
     *
     * @return the value of bot_customer_detail.contack_ext
     *
     * @mbg.generated
     */
    public String getContackExt() {
        return contackExt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_customer_detail.contack_ext
     *
     * @param contackExt the value for bot_customer_detail.contack_ext
     *
     * @mbg.generated
     */
    public void setContackExt(String contackExt) {
        this.contackExt = contackExt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_customer_detail.sync_time
     *
     * @return the value of bot_customer_detail.sync_time
     *
     * @mbg.generated
     */
    public LocalDateTime getSyncTime() {
        return syncTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_customer_detail.sync_time
     *
     * @param syncTime the value for bot_customer_detail.sync_time
     *
     * @mbg.generated
     */
    public void setSyncTime(LocalDateTime syncTime) {
        this.syncTime = syncTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_customer_detail.create_time
     *
     * @return the value of bot_customer_detail.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_customer_detail.create_time
     *
     * @param createTime the value for bot_customer_detail.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_customer_detail.update_time
     *
     * @return the value of bot_customer_detail.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_customer_detail.update_time
     *
     * @param updateTime the value for bot_customer_detail.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_customer_detail
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", bindId=").append(bindId);
        sb.append(", botType=").append(botType);
        sb.append(", name=").append(name);
        sb.append(", contactId=").append(contactId);
        sb.append(", contactType=").append(contactType);
        sb.append(", contackOrgType=").append(contackOrgType);
        sb.append(", nickName=").append(nickName);
        sb.append(", telNum=").append(telNum);
        sb.append(", contackExt=").append(contackExt);
        sb.append(", syncTime=").append(syncTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_customer_detail
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BotCustomerDetail other = (BotCustomerDetail) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getBindId() == null ? other.getBindId() == null : this.getBindId().equals(other.getBindId()))
            && (this.getBotType() == null ? other.getBotType() == null : this.getBotType().equals(other.getBotType()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getContactId() == null ? other.getContactId() == null : this.getContactId().equals(other.getContactId()))
            && (this.getContactType() == null ? other.getContactType() == null : this.getContactType().equals(other.getContactType()))
            && (this.getContackOrgType() == null ? other.getContackOrgType() == null : this.getContackOrgType().equals(other.getContackOrgType()))
            && (this.getNickName() == null ? other.getNickName() == null : this.getNickName().equals(other.getNickName()))
            && (this.getTelNum() == null ? other.getTelNum() == null : this.getTelNum().equals(other.getTelNum()))
            && (this.getContackExt() == null ? other.getContackExt() == null : this.getContackExt().equals(other.getContackExt()))
            && (this.getSyncTime() == null ? other.getSyncTime() == null : this.getSyncTime().equals(other.getSyncTime()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_customer_detail
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getBindId() == null) ? 0 : getBindId().hashCode());
        result = prime * result + ((getBotType() == null) ? 0 : getBotType().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getContactId() == null) ? 0 : getContactId().hashCode());
        result = prime * result + ((getContactType() == null) ? 0 : getContactType().hashCode());
        result = prime * result + ((getContackOrgType() == null) ? 0 : getContackOrgType().hashCode());
        result = prime * result + ((getNickName() == null) ? 0 : getNickName().hashCode());
        result = prime * result + ((getTelNum() == null) ? 0 : getTelNum().hashCode());
        result = prime * result + ((getContackExt() == null) ? 0 : getContackExt().hashCode());
        result = prime * result + ((getSyncTime() == null) ? 0 : getSyncTime().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table bot_customer_detail
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        bindId("bind_id", "bindId", "VARCHAR", false),
        botType("bot_type", "botType", "INTEGER", false),
        name("name", "name", "VARCHAR", true),
        contactId("contact_id", "contactId", "VARCHAR", false),
        contactType("contact_type", "contactType", "INTEGER", false),
        contackOrgType("contack_org_type", "contackOrgType", "INTEGER", false),
        nickName("nick_name", "nickName", "VARCHAR", false),
        telNum("tel_num", "telNum", "VARCHAR", false),
        contackExt("contack_ext", "contackExt", "VARCHAR", false),
        syncTime("sync_time", "syncTime", "TIMESTAMP", false),
        createTime("create_time", "createTime", "TIMESTAMP", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table bot_customer_detail
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table bot_customer_detail
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table bot_customer_detail
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table bot_customer_detail
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table bot_customer_detail
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table bot_customer_detail
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_customer_detail
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_customer_detail
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_customer_detail
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_customer_detail
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_customer_detail
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_customer_detail
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_customer_detail
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_customer_detail
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_customer_detail
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_customer_detail
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}