package org.linlinjava.litemall.db.bot.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class BotDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bot_detail
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bot_detail
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bot_detail
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_detail
     *
     * @mbg.generated
     */
    public BotDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_detail
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_detail
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_detail
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_detail
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_detail
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_detail
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_detail
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_detail
     *
     * @mbg.generated
     */
    public BotDetailExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_detail
     *
     * @mbg.generated
     */
    public BotDetailExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_detail
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_detail
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_detail
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_detail
     *
     * @mbg.generated
     */
    public static Criteria newAndCreateCriteria() {
        BotDetailExample example = new BotDetailExample();
        return example.createCriteria();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_detail
     *
     * @mbg.generated
     */
    public BotDetailExample when(boolean condition, IExampleWhen then) {
        if (condition) {
            then.example(this);
        }
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_detail
     *
     * @mbg.generated
     */
    public BotDetailExample when(boolean condition, IExampleWhen then, IExampleWhen otherwise) {
        if (condition) {
            then.example(this);
        } else {
            otherwise.example(this);
        }
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bot_detail
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andIdEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andIdNotEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andIdGreaterThanColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andIdGreaterThanOrEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andIdLessThanColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andIdLessThanOrEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andStaffIdIsNull() {
            addCriterion("staff_id is null");
            return (Criteria) this;
        }

        public Criteria andStaffIdIsNotNull() {
            addCriterion("staff_id is not null");
            return (Criteria) this;
        }

        public Criteria andStaffIdEqualTo(Long value) {
            addCriterion("staff_id =", value, "staffId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andStaffIdEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("staff_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStaffIdNotEqualTo(Long value) {
            addCriterion("staff_id <>", value, "staffId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andStaffIdNotEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("staff_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStaffIdGreaterThan(Long value) {
            addCriterion("staff_id >", value, "staffId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andStaffIdGreaterThanColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("staff_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStaffIdGreaterThanOrEqualTo(Long value) {
            addCriterion("staff_id >=", value, "staffId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andStaffIdGreaterThanOrEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("staff_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStaffIdLessThan(Long value) {
            addCriterion("staff_id <", value, "staffId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andStaffIdLessThanColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("staff_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStaffIdLessThanOrEqualTo(Long value) {
            addCriterion("staff_id <=", value, "staffId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andStaffIdLessThanOrEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("staff_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStaffIdIn(List<Long> values) {
            addCriterion("staff_id in", values, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdNotIn(List<Long> values) {
            addCriterion("staff_id not in", values, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdBetween(Long value1, Long value2) {
            addCriterion("staff_id between", value1, value2, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdNotBetween(Long value1, Long value2) {
            addCriterion("staff_id not between", value1, value2, "staffId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIsNull() {
            addCriterion("customer_id is null");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIsNotNull() {
            addCriterion("customer_id is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerIdEqualTo(Long value) {
            addCriterion("customer_id =", value, "customerId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andCustomerIdEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("customer_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotEqualTo(Long value) {
            addCriterion("customer_id <>", value, "customerId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andCustomerIdNotEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("customer_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCustomerIdGreaterThan(Long value) {
            addCriterion("customer_id >", value, "customerId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andCustomerIdGreaterThanColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("customer_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCustomerIdGreaterThanOrEqualTo(Long value) {
            addCriterion("customer_id >=", value, "customerId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andCustomerIdGreaterThanOrEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("customer_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCustomerIdLessThan(Long value) {
            addCriterion("customer_id <", value, "customerId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andCustomerIdLessThanColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("customer_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCustomerIdLessThanOrEqualTo(Long value) {
            addCriterion("customer_id <=", value, "customerId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andCustomerIdLessThanOrEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("customer_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCustomerIdIn(List<Long> values) {
            addCriterion("customer_id in", values, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotIn(List<Long> values) {
            addCriterion("customer_id not in", values, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdBetween(Long value1, Long value2) {
            addCriterion("customer_id between", value1, value2, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotBetween(Long value1, Long value2) {
            addCriterion("customer_id not between", value1, value2, "customerId");
            return (Criteria) this;
        }

        public Criteria andBotTokenIsNull() {
            addCriterion("bot_token is null");
            return (Criteria) this;
        }

        public Criteria andBotTokenIsNotNull() {
            addCriterion("bot_token is not null");
            return (Criteria) this;
        }

        public Criteria andBotTokenEqualTo(String value) {
            addCriterion("bot_token =", value, "botToken");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andBotTokenEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("bot_token = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBotTokenNotEqualTo(String value) {
            addCriterion("bot_token <>", value, "botToken");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andBotTokenNotEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("bot_token <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBotTokenGreaterThan(String value) {
            addCriterion("bot_token >", value, "botToken");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andBotTokenGreaterThanColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("bot_token > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBotTokenGreaterThanOrEqualTo(String value) {
            addCriterion("bot_token >=", value, "botToken");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andBotTokenGreaterThanOrEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("bot_token >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBotTokenLessThan(String value) {
            addCriterion("bot_token <", value, "botToken");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andBotTokenLessThanColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("bot_token < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBotTokenLessThanOrEqualTo(String value) {
            addCriterion("bot_token <=", value, "botToken");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andBotTokenLessThanOrEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("bot_token <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBotTokenLike(String value) {
            addCriterion("bot_token like", value, "botToken");
            return (Criteria) this;
        }

        public Criteria andBotTokenNotLike(String value) {
            addCriterion("bot_token not like", value, "botToken");
            return (Criteria) this;
        }

        public Criteria andBotTokenIn(List<String> values) {
            addCriterion("bot_token in", values, "botToken");
            return (Criteria) this;
        }

        public Criteria andBotTokenNotIn(List<String> values) {
            addCriterion("bot_token not in", values, "botToken");
            return (Criteria) this;
        }

        public Criteria andBotTokenBetween(String value1, String value2) {
            addCriterion("bot_token between", value1, value2, "botToken");
            return (Criteria) this;
        }

        public Criteria andBotTokenNotBetween(String value1, String value2) {
            addCriterion("bot_token not between", value1, value2, "botToken");
            return (Criteria) this;
        }

        public Criteria andBotTypeIsNull() {
            addCriterion("bot_type is null");
            return (Criteria) this;
        }

        public Criteria andBotTypeIsNotNull() {
            addCriterion("bot_type is not null");
            return (Criteria) this;
        }

        public Criteria andBotTypeEqualTo(Integer value) {
            addCriterion("bot_type =", value, "botType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andBotTypeEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("bot_type = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBotTypeNotEqualTo(Integer value) {
            addCriterion("bot_type <>", value, "botType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andBotTypeNotEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("bot_type <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBotTypeGreaterThan(Integer value) {
            addCriterion("bot_type >", value, "botType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andBotTypeGreaterThanColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("bot_type > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBotTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("bot_type >=", value, "botType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andBotTypeGreaterThanOrEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("bot_type >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBotTypeLessThan(Integer value) {
            addCriterion("bot_type <", value, "botType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andBotTypeLessThanColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("bot_type < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBotTypeLessThanOrEqualTo(Integer value) {
            addCriterion("bot_type <=", value, "botType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andBotTypeLessThanOrEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("bot_type <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBotTypeIn(List<Integer> values) {
            addCriterion("bot_type in", values, "botType");
            return (Criteria) this;
        }

        public Criteria andBotTypeNotIn(List<Integer> values) {
            addCriterion("bot_type not in", values, "botType");
            return (Criteria) this;
        }

        public Criteria andBotTypeBetween(Integer value1, Integer value2) {
            addCriterion("bot_type between", value1, value2, "botType");
            return (Criteria) this;
        }

        public Criteria andBotTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("bot_type not between", value1, value2, "botType");
            return (Criteria) this;
        }

        public Criteria andBindIdIsNull() {
            addCriterion("bind_id is null");
            return (Criteria) this;
        }

        public Criteria andBindIdIsNotNull() {
            addCriterion("bind_id is not null");
            return (Criteria) this;
        }

        public Criteria andBindIdEqualTo(String value) {
            addCriterion("bind_id =", value, "bindId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andBindIdEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("bind_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBindIdNotEqualTo(String value) {
            addCriterion("bind_id <>", value, "bindId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andBindIdNotEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("bind_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBindIdGreaterThan(String value) {
            addCriterion("bind_id >", value, "bindId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andBindIdGreaterThanColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("bind_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBindIdGreaterThanOrEqualTo(String value) {
            addCriterion("bind_id >=", value, "bindId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andBindIdGreaterThanOrEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("bind_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBindIdLessThan(String value) {
            addCriterion("bind_id <", value, "bindId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andBindIdLessThanColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("bind_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBindIdLessThanOrEqualTo(String value) {
            addCriterion("bind_id <=", value, "bindId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andBindIdLessThanOrEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("bind_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBindIdLike(String value) {
            addCriterion("bind_id like", value, "bindId");
            return (Criteria) this;
        }

        public Criteria andBindIdNotLike(String value) {
            addCriterion("bind_id not like", value, "bindId");
            return (Criteria) this;
        }

        public Criteria andBindIdIn(List<String> values) {
            addCriterion("bind_id in", values, "bindId");
            return (Criteria) this;
        }

        public Criteria andBindIdNotIn(List<String> values) {
            addCriterion("bind_id not in", values, "bindId");
            return (Criteria) this;
        }

        public Criteria andBindIdBetween(String value1, String value2) {
            addCriterion("bind_id between", value1, value2, "bindId");
            return (Criteria) this;
        }

        public Criteria andBindIdNotBetween(String value1, String value2) {
            addCriterion("bind_id not between", value1, value2, "bindId");
            return (Criteria) this;
        }

        public Criteria andOnlineConfIsNull() {
            addCriterion("online_conf is null");
            return (Criteria) this;
        }

        public Criteria andOnlineConfIsNotNull() {
            addCriterion("online_conf is not null");
            return (Criteria) this;
        }

        public Criteria andOnlineConfEqualTo(Integer value) {
            addCriterion("online_conf =", value, "onlineConf");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andOnlineConfEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("online_conf = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOnlineConfNotEqualTo(Integer value) {
            addCriterion("online_conf <>", value, "onlineConf");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andOnlineConfNotEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("online_conf <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOnlineConfGreaterThan(Integer value) {
            addCriterion("online_conf >", value, "onlineConf");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andOnlineConfGreaterThanColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("online_conf > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOnlineConfGreaterThanOrEqualTo(Integer value) {
            addCriterion("online_conf >=", value, "onlineConf");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andOnlineConfGreaterThanOrEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("online_conf >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOnlineConfLessThan(Integer value) {
            addCriterion("online_conf <", value, "onlineConf");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andOnlineConfLessThanColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("online_conf < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOnlineConfLessThanOrEqualTo(Integer value) {
            addCriterion("online_conf <=", value, "onlineConf");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andOnlineConfLessThanOrEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("online_conf <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOnlineConfIn(List<Integer> values) {
            addCriterion("online_conf in", values, "onlineConf");
            return (Criteria) this;
        }

        public Criteria andOnlineConfNotIn(List<Integer> values) {
            addCriterion("online_conf not in", values, "onlineConf");
            return (Criteria) this;
        }

        public Criteria andOnlineConfBetween(Integer value1, Integer value2) {
            addCriterion("online_conf between", value1, value2, "onlineConf");
            return (Criteria) this;
        }

        public Criteria andOnlineConfNotBetween(Integer value1, Integer value2) {
            addCriterion("online_conf not between", value1, value2, "onlineConf");
            return (Criteria) this;
        }

        public Criteria andTiketIdIsNull() {
            addCriterion("tiket_id is null");
            return (Criteria) this;
        }

        public Criteria andTiketIdIsNotNull() {
            addCriterion("tiket_id is not null");
            return (Criteria) this;
        }

        public Criteria andTiketIdEqualTo(Integer value) {
            addCriterion("tiket_id =", value, "tiketId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andTiketIdEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("tiket_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTiketIdNotEqualTo(Integer value) {
            addCriterion("tiket_id <>", value, "tiketId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andTiketIdNotEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("tiket_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTiketIdGreaterThan(Integer value) {
            addCriterion("tiket_id >", value, "tiketId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andTiketIdGreaterThanColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("tiket_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTiketIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("tiket_id >=", value, "tiketId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andTiketIdGreaterThanOrEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("tiket_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTiketIdLessThan(Integer value) {
            addCriterion("tiket_id <", value, "tiketId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andTiketIdLessThanColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("tiket_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTiketIdLessThanOrEqualTo(Integer value) {
            addCriterion("tiket_id <=", value, "tiketId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andTiketIdLessThanOrEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("tiket_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTiketIdIn(List<Integer> values) {
            addCriterion("tiket_id in", values, "tiketId");
            return (Criteria) this;
        }

        public Criteria andTiketIdNotIn(List<Integer> values) {
            addCriterion("tiket_id not in", values, "tiketId");
            return (Criteria) this;
        }

        public Criteria andTiketIdBetween(Integer value1, Integer value2) {
            addCriterion("tiket_id between", value1, value2, "tiketId");
            return (Criteria) this;
        }

        public Criteria andTiketIdNotBetween(Integer value1, Integer value2) {
            addCriterion("tiket_id not between", value1, value2, "tiketId");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("`status` is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("`status` is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("`status` =", value, "status");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andStatusEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("`status` = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("`status` <>", value, "status");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andStatusNotEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("`status` <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("`status` >", value, "status");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andStatusGreaterThanColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("`status` > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("`status` >=", value, "status");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andStatusGreaterThanOrEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("`status` >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("`status` <", value, "status");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andStatusLessThanColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("`status` < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("`status` <=", value, "status");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andStatusLessThanOrEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("`status` <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("`status` in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("`status` not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("`status` between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("`status` not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(LocalDateTime value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("create_time = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(LocalDateTime value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeNotEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("create_time <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(LocalDateTime value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeGreaterThanColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("create_time > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeGreaterThanOrEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("create_time >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(LocalDateTime value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeLessThanColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("create_time < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andCreateTimeLessThanOrEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("create_time <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<LocalDateTime> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<LocalDateTime> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(LocalDateTime value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("update_time = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(LocalDateTime value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeNotEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("update_time <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(LocalDateTime value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeGreaterThanColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("update_time > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeGreaterThanOrEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("update_time >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(LocalDateTime value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeLessThanColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("update_time < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeLessThanOrEqualToColumn(BotDetail.Column column) {
            addCriterion(new StringBuilder("update_time <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<LocalDateTime> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<LocalDateTime> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bot_detail
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        private BotDetailExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        protected Criteria(BotDetailExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public BotDetailExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        @Deprecated
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then) {
            if (condition) {
                then.criteria(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then, ICriteriaWhen otherwise) {
            if (condition) {
                then.criteria(this);
            } else {
                otherwise.criteria(this);
            }
            return this;
        }

        @Deprecated
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table bot_detail
             *
             * @mbg.generated
             */
            Criteria add(Criteria add);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bot_detail
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    public interface ICriteriaWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        void criteria(Criteria criteria);
    }

    public interface IExampleWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        void example(org.linlinjava.litemall.db.bot.domain.BotDetailExample example);
    }
}