package org.linlinjava.litemall.db.bot.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class BotDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_detail.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_detail.staff_id
     *
     * @mbg.generated
     */
    private Long staffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_detail.customer_id
     *
     * @mbg.generated
     */
    private Long customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_detail.bot_token
     *
     * @mbg.generated
     */
    private String botToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_detail.bot_type
     *
     * @mbg.generated
     */
    private Integer botType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_detail.bind_id
     *
     * @mbg.generated
     */
    private String bindId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_detail.online_conf
     *
     * @mbg.generated
     */
    private Integer onlineConf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_detail.tiket_id
     *
     * @mbg.generated
     */
    private Integer tiketId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_detail.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_detail.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_detail.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_detail.id
     *
     * @return the value of bot_detail.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_detail.id
     *
     * @param id the value for bot_detail.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_detail.staff_id
     *
     * @return the value of bot_detail.staff_id
     *
     * @mbg.generated
     */
    public Long getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_detail.staff_id
     *
     * @param staffId the value for bot_detail.staff_id
     *
     * @mbg.generated
     */
    public void setStaffId(Long staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_detail.customer_id
     *
     * @return the value of bot_detail.customer_id
     *
     * @mbg.generated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_detail.customer_id
     *
     * @param customerId the value for bot_detail.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_detail.bot_token
     *
     * @return the value of bot_detail.bot_token
     *
     * @mbg.generated
     */
    public String getBotToken() {
        return botToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_detail.bot_token
     *
     * @param botToken the value for bot_detail.bot_token
     *
     * @mbg.generated
     */
    public void setBotToken(String botToken) {
        this.botToken = botToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_detail.bot_type
     *
     * @return the value of bot_detail.bot_type
     *
     * @mbg.generated
     */
    public Integer getBotType() {
        return botType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_detail.bot_type
     *
     * @param botType the value for bot_detail.bot_type
     *
     * @mbg.generated
     */
    public void setBotType(Integer botType) {
        this.botType = botType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_detail.bind_id
     *
     * @return the value of bot_detail.bind_id
     *
     * @mbg.generated
     */
    public String getBindId() {
        return bindId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_detail.bind_id
     *
     * @param bindId the value for bot_detail.bind_id
     *
     * @mbg.generated
     */
    public void setBindId(String bindId) {
        this.bindId = bindId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_detail.online_conf
     *
     * @return the value of bot_detail.online_conf
     *
     * @mbg.generated
     */
    public Integer getOnlineConf() {
        return onlineConf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_detail.online_conf
     *
     * @param onlineConf the value for bot_detail.online_conf
     *
     * @mbg.generated
     */
    public void setOnlineConf(Integer onlineConf) {
        this.onlineConf = onlineConf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_detail.tiket_id
     *
     * @return the value of bot_detail.tiket_id
     *
     * @mbg.generated
     */
    public Integer getTiketId() {
        return tiketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_detail.tiket_id
     *
     * @param tiketId the value for bot_detail.tiket_id
     *
     * @mbg.generated
     */
    public void setTiketId(Integer tiketId) {
        this.tiketId = tiketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_detail.status
     *
     * @return the value of bot_detail.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_detail.status
     *
     * @param status the value for bot_detail.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_detail.create_time
     *
     * @return the value of bot_detail.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_detail.create_time
     *
     * @param createTime the value for bot_detail.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_detail.update_time
     *
     * @return the value of bot_detail.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_detail.update_time
     *
     * @param updateTime the value for bot_detail.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_detail
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", staffId=").append(staffId);
        sb.append(", customerId=").append(customerId);
        sb.append(", botToken=").append(botToken);
        sb.append(", botType=").append(botType);
        sb.append(", bindId=").append(bindId);
        sb.append(", onlineConf=").append(onlineConf);
        sb.append(", tiketId=").append(tiketId);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_detail
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BotDetail other = (BotDetail) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getStaffId() == null ? other.getStaffId() == null : this.getStaffId().equals(other.getStaffId()))
            && (this.getCustomerId() == null ? other.getCustomerId() == null : this.getCustomerId().equals(other.getCustomerId()))
            && (this.getBotToken() == null ? other.getBotToken() == null : this.getBotToken().equals(other.getBotToken()))
            && (this.getBotType() == null ? other.getBotType() == null : this.getBotType().equals(other.getBotType()))
            && (this.getBindId() == null ? other.getBindId() == null : this.getBindId().equals(other.getBindId()))
            && (this.getOnlineConf() == null ? other.getOnlineConf() == null : this.getOnlineConf().equals(other.getOnlineConf()))
            && (this.getTiketId() == null ? other.getTiketId() == null : this.getTiketId().equals(other.getTiketId()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_detail
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getStaffId() == null) ? 0 : getStaffId().hashCode());
        result = prime * result + ((getCustomerId() == null) ? 0 : getCustomerId().hashCode());
        result = prime * result + ((getBotToken() == null) ? 0 : getBotToken().hashCode());
        result = prime * result + ((getBotType() == null) ? 0 : getBotType().hashCode());
        result = prime * result + ((getBindId() == null) ? 0 : getBindId().hashCode());
        result = prime * result + ((getOnlineConf() == null) ? 0 : getOnlineConf().hashCode());
        result = prime * result + ((getTiketId() == null) ? 0 : getTiketId().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table bot_detail
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        staffId("staff_id", "staffId", "BIGINT", false),
        customerId("customer_id", "customerId", "BIGINT", false),
        botToken("bot_token", "botToken", "VARCHAR", false),
        botType("bot_type", "botType", "INTEGER", false),
        bindId("bind_id", "bindId", "VARCHAR", false),
        onlineConf("online_conf", "onlineConf", "INTEGER", false),
        tiketId("tiket_id", "tiketId", "INTEGER", false),
        status("status", "status", "INTEGER", true),
        createTime("create_time", "createTime", "TIMESTAMP", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_detail
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}