package org.linlinjava.litemall.db.bot.domain;

import java.util.ArrayList;
import java.util.Arrays;

public class BotTaskWithBLOBs extends BotTask {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_task.conf
     *
     * @mbg.generated
     */
    private String conf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_task.schedule_conf
     *
     * @mbg.generated
     */
    private String scheduleConf;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_task.conf
     *
     * @return the value of bot_task.conf
     *
     * @mbg.generated
     */
    public String getConf() {
        return conf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_task.conf
     *
     * @param conf the value for bot_task.conf
     *
     * @mbg.generated
     */
    public void setConf(String conf) {
        this.conf = conf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_task.schedule_conf
     *
     * @return the value of bot_task.schedule_conf
     *
     * @mbg.generated
     */
    public String getScheduleConf() {
        return scheduleConf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_task.schedule_conf
     *
     * @param scheduleConf the value for bot_task.schedule_conf
     *
     * @mbg.generated
     */
    public void setScheduleConf(String scheduleConf) {
        this.scheduleConf = scheduleConf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_task
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", conf=").append(conf);
        sb.append(", scheduleConf=").append(scheduleConf);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_task
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BotTaskWithBLOBs other = (BotTaskWithBLOBs) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getBindId() == null ? other.getBindId() == null : this.getBindId().equals(other.getBindId()))
            && (this.getBotType() == null ? other.getBotType() == null : this.getBotType().equals(other.getBotType()))
            && (this.getTaskType() == null ? other.getTaskType() == null : this.getTaskType().equals(other.getTaskType()))
            && (this.getRunStatus() == null ? other.getRunStatus() == null : this.getRunStatus().equals(other.getRunStatus()))
            && (this.getProcessing() == null ? other.getProcessing() == null : this.getProcessing().equals(other.getProcessing()))
            && (this.getProcessionTime() == null ? other.getProcessionTime() == null : this.getProcessionTime().equals(other.getProcessionTime()))
            && (this.getScheduleType() == null ? other.getScheduleType() == null : this.getScheduleType().equals(other.getScheduleType()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getConf() == null ? other.getConf() == null : this.getConf().equals(other.getConf()))
            && (this.getScheduleConf() == null ? other.getScheduleConf() == null : this.getScheduleConf().equals(other.getScheduleConf()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_task
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getBindId() == null) ? 0 : getBindId().hashCode());
        result = prime * result + ((getBotType() == null) ? 0 : getBotType().hashCode());
        result = prime * result + ((getTaskType() == null) ? 0 : getTaskType().hashCode());
        result = prime * result + ((getRunStatus() == null) ? 0 : getRunStatus().hashCode());
        result = prime * result + ((getProcessing() == null) ? 0 : getProcessing().hashCode());
        result = prime * result + ((getProcessionTime() == null) ? 0 : getProcessionTime().hashCode());
        result = prime * result + ((getScheduleType() == null) ? 0 : getScheduleType().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getConf() == null) ? 0 : getConf().hashCode());
        result = prime * result + ((getScheduleConf() == null) ? 0 : getScheduleConf().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table bot_task
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        bindId("bind_id", "bindId", "BIGINT", false),
        botType("bot_type", "botType", "INTEGER", false),
        taskType("task_type", "taskType", "INTEGER", false),
        runStatus("run_status", "runStatus", "INTEGER", false),
        processing("processing", "processing", "INTEGER", false),
        processionTime("procession_time", "processionTime", "BIGINT", false),
        scheduleType("schedule_type", "scheduleType", "INTEGER", false),
        status("status", "status", "INTEGER", true),
        createTime("create_time", "createTime", "TIMESTAMP", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false),
        conf("conf", "conf", "LONGVARCHAR", false),
        scheduleConf("schedule_conf", "scheduleConf", "LONGVARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table bot_task
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table bot_task
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table bot_task
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table bot_task
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table bot_task
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table bot_task
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_task
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_task
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_task
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_task
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_task
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_task
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_task
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_task
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_task
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_task
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}