package org.linlinjava.litemall.db.bot.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class BotTask {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_task.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_task.bind_id
     *
     * @mbg.generated
     */
    private Long bindId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_task.bot_type
     *
     * @mbg.generated
     */
    private Integer botType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_task.task_type
     *
     * @mbg.generated
     */
    private Integer taskType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_task.run_status
     *
     * @mbg.generated
     */
    private Integer runStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_task.processing
     *
     * @mbg.generated
     */
    private Integer processing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_task.procession_time
     *
     * @mbg.generated
     */
    private Long processionTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_task.schedule_type
     *
     * @mbg.generated
     */
    private Integer scheduleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_task.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_task.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_task.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_task.id
     *
     * @return the value of bot_task.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_task.id
     *
     * @param id the value for bot_task.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_task.bind_id
     *
     * @return the value of bot_task.bind_id
     *
     * @mbg.generated
     */
    public Long getBindId() {
        return bindId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_task.bind_id
     *
     * @param bindId the value for bot_task.bind_id
     *
     * @mbg.generated
     */
    public void setBindId(Long bindId) {
        this.bindId = bindId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_task.bot_type
     *
     * @return the value of bot_task.bot_type
     *
     * @mbg.generated
     */
    public Integer getBotType() {
        return botType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_task.bot_type
     *
     * @param botType the value for bot_task.bot_type
     *
     * @mbg.generated
     */
    public void setBotType(Integer botType) {
        this.botType = botType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_task.task_type
     *
     * @return the value of bot_task.task_type
     *
     * @mbg.generated
     */
    public Integer getTaskType() {
        return taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_task.task_type
     *
     * @param taskType the value for bot_task.task_type
     *
     * @mbg.generated
     */
    public void setTaskType(Integer taskType) {
        this.taskType = taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_task.run_status
     *
     * @return the value of bot_task.run_status
     *
     * @mbg.generated
     */
    public Integer getRunStatus() {
        return runStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_task.run_status
     *
     * @param runStatus the value for bot_task.run_status
     *
     * @mbg.generated
     */
    public void setRunStatus(Integer runStatus) {
        this.runStatus = runStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_task.processing
     *
     * @return the value of bot_task.processing
     *
     * @mbg.generated
     */
    public Integer getProcessing() {
        return processing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_task.processing
     *
     * @param processing the value for bot_task.processing
     *
     * @mbg.generated
     */
    public void setProcessing(Integer processing) {
        this.processing = processing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_task.procession_time
     *
     * @return the value of bot_task.procession_time
     *
     * @mbg.generated
     */
    public Long getProcessionTime() {
        return processionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_task.procession_time
     *
     * @param processionTime the value for bot_task.procession_time
     *
     * @mbg.generated
     */
    public void setProcessionTime(Long processionTime) {
        this.processionTime = processionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_task.schedule_type
     *
     * @return the value of bot_task.schedule_type
     *
     * @mbg.generated
     */
    public Integer getScheduleType() {
        return scheduleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_task.schedule_type
     *
     * @param scheduleType the value for bot_task.schedule_type
     *
     * @mbg.generated
     */
    public void setScheduleType(Integer scheduleType) {
        this.scheduleType = scheduleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_task.status
     *
     * @return the value of bot_task.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_task.status
     *
     * @param status the value for bot_task.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_task.create_time
     *
     * @return the value of bot_task.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_task.create_time
     *
     * @param createTime the value for bot_task.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_task.update_time
     *
     * @return the value of bot_task.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_task.update_time
     *
     * @param updateTime the value for bot_task.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_task
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", bindId=").append(bindId);
        sb.append(", botType=").append(botType);
        sb.append(", taskType=").append(taskType);
        sb.append(", runStatus=").append(runStatus);
        sb.append(", processing=").append(processing);
        sb.append(", processionTime=").append(processionTime);
        sb.append(", scheduleType=").append(scheduleType);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_task
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BotTask other = (BotTask) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getBindId() == null ? other.getBindId() == null : this.getBindId().equals(other.getBindId()))
            && (this.getBotType() == null ? other.getBotType() == null : this.getBotType().equals(other.getBotType()))
            && (this.getTaskType() == null ? other.getTaskType() == null : this.getTaskType().equals(other.getTaskType()))
            && (this.getRunStatus() == null ? other.getRunStatus() == null : this.getRunStatus().equals(other.getRunStatus()))
            && (this.getProcessing() == null ? other.getProcessing() == null : this.getProcessing().equals(other.getProcessing()))
            && (this.getProcessionTime() == null ? other.getProcessionTime() == null : this.getProcessionTime().equals(other.getProcessionTime()))
            && (this.getScheduleType() == null ? other.getScheduleType() == null : this.getScheduleType().equals(other.getScheduleType()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_task
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getBindId() == null) ? 0 : getBindId().hashCode());
        result = prime * result + ((getBotType() == null) ? 0 : getBotType().hashCode());
        result = prime * result + ((getTaskType() == null) ? 0 : getTaskType().hashCode());
        result = prime * result + ((getRunStatus() == null) ? 0 : getRunStatus().hashCode());
        result = prime * result + ((getProcessing() == null) ? 0 : getProcessing().hashCode());
        result = prime * result + ((getProcessionTime() == null) ? 0 : getProcessionTime().hashCode());
        result = prime * result + ((getScheduleType() == null) ? 0 : getScheduleType().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table bot_task
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        bindId("bind_id", "bindId", "BIGINT", false),
        botType("bot_type", "botType", "INTEGER", false),
        taskType("task_type", "taskType", "INTEGER", false),
        runStatus("run_status", "runStatus", "INTEGER", false),
        processing("processing", "processing", "INTEGER", false),
        processionTime("procession_time", "processionTime", "BIGINT", false),
        scheduleType("schedule_type", "scheduleType", "INTEGER", false),
        status("status", "status", "INTEGER", true),
        createTime("create_time", "createTime", "TIMESTAMP", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false),
        conf("conf", "conf", "LONGVARCHAR", false),
        scheduleConf("schedule_conf", "scheduleConf", "LONGVARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table bot_task
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table bot_task
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table bot_task
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table bot_task
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table bot_task
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table bot_task
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_task
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_task
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_task
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_task
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_task
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_task
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_task
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_task
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_task
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table bot_task
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}