spring:
  profiles:
    active: db, core, admin
  messages:
    encoding: UTF-8

server:
  port: 8083

logging:
  level:
    root:  INFO
    org.springframework:  INFO
    org.mybatis:  INFO
    org.linlinjava.litemall.admin:  INFO
    org.linlinjava.litemall:  ERROR

swagger:
  production: false

grpc:
  server:
    port: 8084
    inProcessName: hello-service
    reflectionServiceEnabled: true

  client:
    hello-service:
      address: static://127.0.0.1:8084
      negotiationType: plaintext