// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serv.proto

package com.hanzhan.promotion.grpc;

public final class HelloWorldProto {
  private HelloWorldProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hanzhan_promotion_grpc_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hanzhan_promotion_grpc_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hanzhan_promotion_grpc_HelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hanzhan_promotion_grpc_HelloReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nserv.proto\022\032com.hanzhan.promotion.grpc" +
      "\"\034\n\014HelloRequest\022\014\n\004name\030\001 \001(\t\"\035\n\nHelloR" +
      "eply\022\017\n\007message\030\001 \001(\t2k\n\tMyService\022^\n\010Sa" +
      "yHello\022(.com.hanzhan.promotion.grpc.Hell" +
      "oRequest\032&.com.hanzhan.promotion.grpc.He" +
      "lloReply\"\000B/\n\032com.hanzhan.promotion.grpc" +
      "B\017HelloWorldProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_hanzhan_promotion_grpc_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_hanzhan_promotion_grpc_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hanzhan_promotion_grpc_HelloRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_hanzhan_promotion_grpc_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_hanzhan_promotion_grpc_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hanzhan_promotion_grpc_HelloReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
