package org.linlinjava.litemall.db.bot.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.bot.domain.BotCustomerDetail;
import org.linlinjava.litemall.db.bot.domain.BotCustomerDetailExample;

public interface BotCustomerDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_customer_detail
     *
     * @mbg.generated
     */
    long countByExample(BotCustomerDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_customer_detail
     *
     * @mbg.generated
     */
    int deleteByExample(BotCustomerDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_customer_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_customer_detail
     *
     * @mbg.generated
     */
    int insert(BotCustomerDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_customer_detail
     *
     * @mbg.generated
     */
    int insertSelective(BotCustomerDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_customer_detail
     *
     * @mbg.generated
     */
    BotCustomerDetail selectOneByExample(BotCustomerDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_customer_detail
     *
     * @mbg.generated
     */
    BotCustomerDetail selectOneByExampleSelective(@Param("example") BotCustomerDetailExample example, @Param("selective") BotCustomerDetail.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_customer_detail
     *
     * @mbg.generated
     */
    List<BotCustomerDetail> selectByExampleSelective(@Param("example") BotCustomerDetailExample example, @Param("selective") BotCustomerDetail.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_customer_detail
     *
     * @mbg.generated
     */
    List<BotCustomerDetail> selectByExample(BotCustomerDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_customer_detail
     *
     * @mbg.generated
     */
    BotCustomerDetail selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") BotCustomerDetail.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_customer_detail
     *
     * @mbg.generated
     */
    BotCustomerDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_customer_detail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BotCustomerDetail record, @Param("example") BotCustomerDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_customer_detail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BotCustomerDetail record, @Param("example") BotCustomerDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_customer_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BotCustomerDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_customer_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BotCustomerDetail record);
}