package org.linlinjava.litemall.db.bot.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.bot.domain.BotDetail;
import org.linlinjava.litemall.db.bot.domain.BotDetailExample;

public interface BotDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_detail
     *
     * @mbg.generated
     */
    long countByExample(BotDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_detail
     *
     * @mbg.generated
     */
    int deleteByExample(BotDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_detail
     *
     * @mbg.generated
     */
    int insert(BotDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_detail
     *
     * @mbg.generated
     */
    int insertSelective(BotDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_detail
     *
     * @mbg.generated
     */
    BotDetail selectOneByExample(BotDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_detail
     *
     * @mbg.generated
     */
    BotDetail selectOneByExampleSelective(@Param("example") BotDetailExample example, @Param("selective") BotDetail.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_detail
     *
     * @mbg.generated
     */
    List<BotDetail> selectByExampleSelective(@Param("example") BotDetailExample example, @Param("selective") BotDetail.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_detail
     *
     * @mbg.generated
     */
    List<BotDetail> selectByExample(BotDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_detail
     *
     * @mbg.generated
     */
    BotDetail selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") BotDetail.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_detail
     *
     * @mbg.generated
     */
    BotDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_detail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BotDetail record, @Param("example") BotDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_detail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BotDetail record, @Param("example") BotDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BotDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BotDetail record);
}