package org.linlinjava.litemall.db.bot.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.bot.domain.BotTicket;
import org.linlinjava.litemall.db.bot.domain.BotTicketExample;

public interface BotTicketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_ticket
     *
     * @mbg.generated
     */
    long countByExample(BotTicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_ticket
     *
     * @mbg.generated
     */
    int deleteByExample(BotTicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_ticket
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_ticket
     *
     * @mbg.generated
     */
    int insert(BotTicket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_ticket
     *
     * @mbg.generated
     */
    int insertSelective(BotTicket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_ticket
     *
     * @mbg.generated
     */
    BotTicket selectOneByExample(BotTicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_ticket
     *
     * @mbg.generated
     */
    BotTicket selectOneByExampleSelective(@Param("example") BotTicketExample example, @Param("selective") BotTicket.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_ticket
     *
     * @mbg.generated
     */
    List<BotTicket> selectByExampleSelective(@Param("example") BotTicketExample example, @Param("selective") BotTicket.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_ticket
     *
     * @mbg.generated
     */
    List<BotTicket> selectByExample(BotTicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_ticket
     *
     * @mbg.generated
     */
    BotTicket selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") BotTicket.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_ticket
     *
     * @mbg.generated
     */
    BotTicket selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_ticket
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BotTicket record, @Param("example") BotTicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_ticket
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BotTicket record, @Param("example") BotTicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_ticket
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BotTicket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_ticket
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BotTicket record);
}