package org.linlinjava.litemall.db.bot.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.bot.domain.BotTicketChargeHistory;
import org.linlinjava.litemall.db.bot.domain.BotTicketChargeHistoryExample;

public interface BotTicketChargeHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_ticket_charge_history
     *
     * @mbg.generated
     */
    long countByExample(BotTicketChargeHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_ticket_charge_history
     *
     * @mbg.generated
     */
    int deleteByExample(BotTicketChargeHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_ticket_charge_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_ticket_charge_history
     *
     * @mbg.generated
     */
    int insert(BotTicketChargeHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_ticket_charge_history
     *
     * @mbg.generated
     */
    int insertSelective(BotTicketChargeHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_ticket_charge_history
     *
     * @mbg.generated
     */
    BotTicketChargeHistory selectOneByExample(BotTicketChargeHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_ticket_charge_history
     *
     * @mbg.generated
     */
    BotTicketChargeHistory selectOneByExampleSelective(@Param("example") BotTicketChargeHistoryExample example, @Param("selective") BotTicketChargeHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_ticket_charge_history
     *
     * @mbg.generated
     */
    List<BotTicketChargeHistory> selectByExampleSelective(@Param("example") BotTicketChargeHistoryExample example, @Param("selective") BotTicketChargeHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_ticket_charge_history
     *
     * @mbg.generated
     */
    List<BotTicketChargeHistory> selectByExample(BotTicketChargeHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_ticket_charge_history
     *
     * @mbg.generated
     */
    BotTicketChargeHistory selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") BotTicketChargeHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_ticket_charge_history
     *
     * @mbg.generated
     */
    BotTicketChargeHistory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_ticket_charge_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BotTicketChargeHistory record, @Param("example") BotTicketChargeHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_ticket_charge_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BotTicketChargeHistory record, @Param("example") BotTicketChargeHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_ticket_charge_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BotTicketChargeHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_ticket_charge_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BotTicketChargeHistory record);
}