package org.linlinjava.litemall.db.bot.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.bot.domain.BotTask;
import org.linlinjava.litemall.db.bot.domain.BotTaskExample;
import org.linlinjava.litemall.db.bot.domain.BotTaskWithBLOBs;

public interface BotTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_task
     *
     * @mbg.generated
     */
    long countByExample(BotTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_task
     *
     * @mbg.generated
     */
    int deleteByExample(BotTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_task
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_task
     *
     * @mbg.generated
     */
    int insert(BotTaskWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_task
     *
     * @mbg.generated
     */
    int insertSelective(BotTaskWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_task
     *
     * @mbg.generated
     */
    BotTask selectOneByExample(BotTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_task
     *
     * @mbg.generated
     */
    BotTaskWithBLOBs selectOneByExampleSelective(@Param("example") BotTaskExample example, @Param("selective") BotTaskWithBLOBs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_task
     *
     * @mbg.generated
     */
    BotTaskWithBLOBs selectOneByExampleWithBLOBs(BotTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_task
     *
     * @mbg.generated
     */
    List<BotTaskWithBLOBs> selectByExampleSelective(@Param("example") BotTaskExample example, @Param("selective") BotTaskWithBLOBs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_task
     *
     * @mbg.generated
     */
    List<BotTaskWithBLOBs> selectByExampleWithBLOBs(BotTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_task
     *
     * @mbg.generated
     */
    List<BotTask> selectByExample(BotTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_task
     *
     * @mbg.generated
     */
    BotTaskWithBLOBs selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") BotTaskWithBLOBs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_task
     *
     * @mbg.generated
     */
    BotTaskWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_task
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BotTaskWithBLOBs record, @Param("example") BotTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_task
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") BotTaskWithBLOBs record, @Param("example") BotTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_task
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BotTask record, @Param("example") BotTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BotTaskWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(BotTaskWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bot_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BotTask record);
}