package org.linlinjava.litemall.db.bot.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.bot.domain.StaffInfo;
import org.linlinjava.litemall.db.bot.domain.StaffInfoExample;

public interface StaffInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_info
     *
     * @mbg.generated
     */
    long countByExample(StaffInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_info
     *
     * @mbg.generated
     */
    int deleteByExample(StaffInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_info
     *
     * @mbg.generated
     */
    int insert(StaffInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_info
     *
     * @mbg.generated
     */
    int insertSelective(StaffInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_info
     *
     * @mbg.generated
     */
    StaffInfo selectOneByExample(StaffInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_info
     *
     * @mbg.generated
     */
    StaffInfo selectOneByExampleSelective(@Param("example") StaffInfoExample example, @Param("selective") StaffInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_info
     *
     * @mbg.generated
     */
    List<StaffInfo> selectByExampleSelective(@Param("example") StaffInfoExample example, @Param("selective") StaffInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_info
     *
     * @mbg.generated
     */
    List<StaffInfo> selectByExample(StaffInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_info
     *
     * @mbg.generated
     */
    StaffInfo selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") StaffInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_info
     *
     * @mbg.generated
     */
    StaffInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") StaffInfo record, @Param("example") StaffInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") StaffInfo record, @Param("example") StaffInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StaffInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StaffInfo record);
}